# Copyright 2025 SUSE LLC
# SPDX-License-Identifier: Apache-2.0

---
header:
  comment: on-failure
  license:
    copyright-owner: SUSE LLC
    software-name: mcp-server-trento
    content: |
      Copyright 2025 SUSE LLC
      SPDX-License-Identifier: Apache-2.0
    pattern: |
      Copyright (?:\d{4}-\d{4}|\d{4}) SUSE LLC
  paths-ignore:
    - .github/
    - .tool-versions
    - CHANGELOG.md
    - LICENSE
    - VERSION
    - go.sum
    - packaging/suse/rpm/systemd/mcp-server-trento.service
