services:
  postgres:
    image: pgvector/pgvector:pg15
    restart: unless-stopped
    container_name: trento-pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trento_rag
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5434:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  example-collector:
    image: arizephoenix/phoenix:latest
    container_name: arizephoenix
    restart: unless-stopped
    ports:
      - "6006:6006"
      - "4317:4317"

volumes:
  pgvector_data:
    driver: local

# go run . agui --gemini-api-key $GEMINI_API_KEY --pg-url "postgres://postgres:postgres@localhost:5434/trento_rag?sslmode=disable"
