# Copyright 2025 SUSE LLC
# SPDX-License-Identifier: Apache-2.0

---
global:
  imagePullSecrets:
    - application-collection

persistence:
  enabled: true
  storageClass: local-path

ollama:
  enabled: false

pipelines:
  enabled: false

ingress:
  enabled: true
  annotations: {}
  host: suse-ai.example.com
  tls: true

extraEnvVars:
  - name: DEFAULT_USER_ROLE
    value: "user"
  - name: WEBUI_NAME
    value: "SUSE AI"
  - name: GLOBAL_LOG_LEVEL
    value: INFO
  - name: RAG_EMBEDDING_MODEL
    value: "sentence-transformers/all-MiniLM-L6-v2"
