# Copyright 2025 SUSE LLC
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: trento-mcp-server
description: A Helm chart for deploying the Trento MCP Server component
type: application
home: https://www.trento-project.io/
maintainers:
  - name: SUSE
    url: https://www.suse.com/
version: 0.1.0
appVersion: "0.1.0"
