# Copyright 2024-2025 SUSE LLC
---
name: Lib - Linters section
on:
  workflow_call:
    inputs:
      golang_version:
        type: string
        required: true

jobs:
  # Job: static-code-analysis
  # Purpose: Run Go static analysis tools (vet, fmt, golangci-lint) to ensure code quality and style.
  static-code-analysis:
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v5
        name: Checkout
      # Read tool versions for environment setup
      - uses: endorama/asdf-parse-tool-versions@v1
        name: Read .tool-versions
        id: tool-versions
      # Setup Go environment
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      # Cache Go modules for faster builds
      - uses: actions/cache@v4
        name: Cache Go modules
        id: go-cache
        with:
          path: ~/go/pkg/mod
          key: go-${{ env.GOLANG_VERSION }}-${{ hashFiles('**/go.sum') }}
      # Run go vet for static analysis
      - name: go vet check
        run: make vet-check
      # Run go fmt to check code formatting
      - name: go fmt check
        run: make fmt-check
      # Run golangci-lint for advanced linting
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          skip-cache: true
          args: "--timeout=5m"

  # Job: linter-license-headers
  # Purpose: Check that all source files have the correct license headers.
  linter-license-headers:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
        name: Checkout
      # Run SkyWalking Eyes to check license headers
      - uses: apache/skywalking-eyes/header@v0.7.0
        name: Check license Headers

  # Job: linter-documentation
  # Purpose: Lint all AsciiDoc documentation files using asciidoctor and a custom script.
  linter-documentation:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v5
        name: Checkout
      # Install asciidoctor for linting .adoc files
      - name: Install asciidoctor
        run: sudo apt-get update && sudo apt-get install -y asciidoctor
      # Run the custom AsciiDoc linter script
      - name: Run AsciiDoc linter
        run: bash hack/linters/asciidoc-linter.sh

  # Job: linter-shellscripts
  # Purpose: Run ShellCheck on all shell scripts to catch common scripting errors.
  linter-shellscripts:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
      # Run ShellCheck linter on shell scripts
      - uses: ludeeus/action-shellcheck@2.0.0
        name: Run ShellCheck
